stages:
  - automated-api-tests

automated-api-tests:
  stage: automated-api-tests
  image: cimg/base:2021.04
  before_script:
    # Installing Postman CLI
    - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  script:
    # Login using your Postman API keys
    - postman login --username $USERNAME --password $PASSWORD --with-api-key $POSTMAN_API_KEY
    - postman collection run "30659137-22b6c1f7-ca03-46ee-9fd5-11ee3c2b32ad"